// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/api/v1/services.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	commons "github.com/jcfug8/daylier-backend/protos/commons"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("protos/api/v1/services.proto", fileDescriptor_4a35d02f31070be3) }

var fileDescriptor_4a35d02f31070be3 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x33, 0xd4, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c,
	0x4e, 0x2d, 0xd6, 0x03, 0x0b, 0x0b, 0xb1, 0x25, 0x16, 0x64, 0xea, 0x95, 0x19, 0x4a, 0xc1, 0x54,
	0x25, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0x15, 0xeb, 0xa7, 0xa7, 0xe6, 0xa5, 0x16, 0x25, 0xe6, 0x40,
	0x54, 0x19, 0x19, 0x72, 0x31, 0x3b, 0x06, 0x78, 0x0a, 0x69, 0x71, 0xb1, 0x04, 0x64, 0xe6, 0xa5,
	0x0b, 0x09, 0xe8, 0x41, 0x95, 0xe9, 0x81, 0xb8, 0x41, 0xa9, 0x85, 0x52, 0xe8, 0x22, 0xc5, 0x4e,
	0x86, 0x51, 0xfa, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x20, 0x19, 0xfd, 0xac, 0xe4, 0xb4, 0xd2,
	0x74, 0x0b, 0xfd, 0x94, 0xc4, 0xca, 0x9c, 0xcc, 0xd4, 0x22, 0xdd, 0xa4, 0xc4, 0xe4, 0xec, 0xd4,
	0xbc, 0x14, 0x7d, 0x14, 0xa7, 0x25, 0xb1, 0x81, 0xb9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x90, 0x38, 0x02, 0xfd, 0xb2, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	Ping(ctx context.Context, in *commons.PingReq, opts ...grpc.CallOption) (*commons.PingRes, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Ping(ctx context.Context, in *commons.PingReq, opts ...grpc.CallOption) (*commons.PingRes, error) {
	out := new(commons.PingRes)
	err := c.cc.Invoke(ctx, "/api.v1.API/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	Ping(context.Context, *commons.PingReq) (*commons.PingRes, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) Ping(ctx context.Context, req *commons.PingReq) (*commons.PingRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(commons.PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.API/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Ping(ctx, req.(*commons.PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _API_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/api/v1/services.proto",
}
